### ISSUE TITLE
GNOME 43 runtime is end-of-life

### ISSUE THREAD

**Issue by JamiKettunen** [flathub/com.github.rafostar.Clapper#21]
Just saw this app on my shrinking `flatpak list --app-runtime=org.gnome.Platform//43` output, nothing too urgent though :)

**Comment by JamiKettunen** [comment]
Update: as of today the GNOME 43 runtime is end-of-life and I saw the following after `flatpak update` (along with other apps starting to switch to the 45 runtime):
```
Info: runtime org.gnome.Platform branch 43 is end-of-life, with reason:
   The GNOME 43 runtime is no longer supported as of September 20, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   com.github.rafostar.Clapper
```
@Rafostar Are there plans to update (to at least 44) this in the near future?

**Comment by Ferenc-** [comment]
@JamiKettunen 
I think the relevant thread is in this PR https://github.com/Rafostar/clapper/pull/344
